homework for 03 and 05
XueleiFan/java-up pull request #11
Opened 2021-11-24 09:10 UTC by jackxu2011

record, and pattern match homework

2021-11-26 05:36 UTC, XueleiFan requested changes
Looks nice to me except a comment in the equals() implementation.

2021-11-26 05:36 UTC, XueleiFan commented on src/main/java/co/ivi/jus/record/review/xuling/SocialSecurityNumber.java
> +        }
这里的实现是这个思考题最难的地方。敏感信息的比较，应该是时间恒定的。也就是说，信息比较计算的时间，只和信息的长度有关，而不能和信息的内容有关系。所以，建议使用java.security.MessageDigest. isEqual(byte[] digesta,           byte[] digestb)来比较敏感信息。

2021-11-26 06:56 UTC, jackxu2011 commented on src/main/java/co/ivi/jus/record/review/xuling/SocialSecurityNumber.java
> +        }
好的，这个主要是为了防止黑客攻击。当时感觉这个没有这么重要，按照这个逻辑，toString方法是不是也需要加密输出。

2021-11-26 08:46 UTC, XueleiFan commented on src/main/java/co/ivi/jus/record/review/xuling/SocialSecurityNumber.java
> +        }
toString有待商榷，要看使用场景怎么用toString了。安全起见，也不建议输出SSN。倒是没有必要加密。

2021-11-27 17:51 UTC, songor commented on src/main/java/co/ivi/jus/record/review/xuling/SocialSecurityNumber.java
> +        }
> 涨姿势
Arrays.equals() is fail fast method.
If there is a hash or key comparison using Arrays.equals(), the attack can fake a hash or key and do the comparison with the actual hash or key. They can measure the time taken for Arrays.equals() to return to understand how many bytes matched the faked hash or key has. After hundreds or thousands of tries, they may reveal the actual hash and key.

2021-11-27 17:53 UTC, songor commented on src/main/java/co/ivi/jus/record/review/xuling/SocialSecurityNumber.java
> +        }
是否可以脱敏显示呢？

2021-11-27 18:57 UTC, XueleiFan commented on src/main/java/co/ivi/jus/record/review/xuling/SocialSecurityNumber.java
> +        }
脱敏显示当然可以。

2021-11-30 08:26 UTC, jackxu2011 commented
add DaysInMonth homework

2021-12-04 05:07 UTC, XueleiFan requested changes
It looks good  to me except a minor comment.

2021-12-04 05:07 UTC, XueleiFan commented on src/main/java/co/ivi/jus/record/review/xuling/SocialSecurityNumber.java
> +        }
这些代码还可以进一步的简化。 第25行到35行删除掉，逻辑上应该没有什么影响。

2021-12-06 03:14 UTC, jackxu2011 commented on src/main/java/co/ivi/jus/record/review/xuling/SocialSecurityNumber.java
> +        }
在逻辑上没有什么问题。这里需要failfast吗?

2021-12-06 03:44 UTC, XueleiFan commented on src/main/java/co/ivi/jus/record/review/xuling/SocialSecurityNumber.java
> +        }
倒不是fail fast，这些代码是冗余的，对于执行结果没有影响。 一般地，从性能和可维护性方面来说，我们不保留、不执行没有用的代码。

2021-12-06 03:45 UTC, merged