Instance Demo.
XueleiFan/java-up pull request #12
Opened 2021-11-24 14:37 UTC by pruidong

The isSquareA and isSquareF methods come from the example method 1 and method 6, but some codes are removed on the original basis.

The isSquare method comes from example method 3, with the extra parentheses removed. The entire method is only one line of code. I think this is what I want.

The methods isSquare, isSquareA, and isSquareF have been tested and meet expectations.

2021-11-25 06:53 UTC, XueleiFan requested changes

2021-11-25 06:53 UTC, XueleiFan commented on src/main/java/co/ivi/jus/instance/review/puruidong/Shape.java
> +    /// nice.
规范的注释，还是使用两个‘/’。

2021-11-25 06:53 UTC, XueleiFan commented on src/main/java/co/ivi/jus/instance/review/puruidong/Shape.java
> +                        shape instanceof Rectangle rect && rect.length == rect.width;
并列的语义，形式上也要对齐（54行，55行）。

2021-11-25 06:53 UTC, XueleiFan commented on src/main/java/co/ivi/jus/instance/review/puruidong/Shape.java
> +        if (shape instanceof Rectangle rect)
条件语句后面，最好总是使用双引号，很多规范都这么要求的。

2021-11-25 13:55 UTC, pruidong commented on src/main/java/co/ivi/jus/instance/review/puruidong/Shape.java
> +    /// nice.
好的，前段时间受Dart影响,大多数时候写三个"///".后面注意下.

2021-11-25 13:55 UTC, pruidong commented on src/main/java/co/ivi/jus/instance/review/puruidong/Shape.java
> +                        shape instanceof Rectangle rect && rect.length == rect.width;
好的，谢谢老师.

2021-11-25 13:56 UTC, pruidong commented on src/main/java/co/ivi/jus/instance/review/puruidong/Shape.java
> +        if (shape instanceof Rectangle rect)
老师说的是大括号把?大部分时候都用了的,在这只是示例,所以没用双括号.

2021-11-26 05:38 UTC, XueleiFan commented on src/main/java/co/ivi/jus/instance/review/puruidong/Shape.java
> +        if (shape instanceof Rectangle rect)
是大括号。

2021-11-26 07:54 UTC, pruidong commented on src/main/java/co/ivi/jus/instance/review/puruidong/Shape.java
> +        if (shape instanceof Rectangle rect)
已处理.

2021-11-26 08:43 UTC, merged