feat(03): homework
XueleiFan/java-up pull request #14
Opened 2021-11-27 18:03 UTC by songor

2021-11-28 05:19 UTC, XueleiFan requested changes
Nice code, except a few concerns of mine.

2021-11-28 05:19 UTC, XueleiFan commented on pom.xml
> +                    </compilerArgs>
Thanks for the configuration update!

2021-11-28 05:19 UTC, XueleiFan commented on src/main/java/co/ivi/jus/record/review/songor/SocialSecurityNumber.java
> +        if (o == null || getClass() != o.getClass()) {
The case "o == null" should has been covered by the clause above (this == o).  It may be better for performance if using "o instanceof SocialSecurityNumber", comparing the call to getClass() method.

2021-11-28 05:19 UTC, XueleiFan commented on src/main/java/co/ivi/jus/record/review/songor/SocialSecurityNumber.java
> +    public byte[] ssn() {
The override here may have problems if copying object.  For example, the newSsnObj, created with code "newSsnObj = new  SocialSecurityNumber(anSsnObj.ssn())", may not equal to the anSsnObj.

2021-11-28 05:19 UTC, XueleiFan commented on src/main/java/co/ivi/jus/record/review/songor/SocialSecurityNumber.java
> +        return Arrays.equals(ssn, other.ssn);
SSN is sensitive information, it would be nice if the comparing could be constant-time.  Normally, we use java.security.MessageDigest. isEqual(byte[] digesta, byte[] digestb) for sensitive information comparing.

2021-11-28 08:37 UTC, songor commented on src/main/java/co/ivi/jus/record/review/songor/SocialSecurityNumber.java
> +        if (o == null || getClass() != o.getClass()) {
https://stackoverflow.com/questions/596462/any-reason-to-prefer-getclass-over-instanceof-when-generating-equals
> The reason that I favor the instanceof approach is that when you use the getClass approach, you have the restriction that objects are only equal to other objects of the same class, the same run time type. If you extend a class and add a couple of innocuous methods to it, then check to see whether some object of the subclass is equal to an object of the super class, even if the objects are equal in all important aspects, you will get the surprising answer that they aren't equal. In fact, this violates a strict interpretation of the Liskov substitution principle, and can lead to very surprising behavior. In Java, it's particularly important because most of the collections (HashTable, etc.) are based on the equals method. If you put a member of the super class in a hash table as the key and then look it up using a subclass instance, you won't find it, because they are not equal.

2021-11-28 08:54 UTC, songor commented on src/main/java/co/ivi/jus/record/review/songor/SocialSecurityNumber.java
> +        return Arrays.equals(ssn, other.ssn);
https://codahale.com/a-lesson-in-timing-attacks/

2021-11-28 09:11 UTC, songor commented on src/main/java/co/ivi/jus/record/review/songor/SocialSecurityNumber.java
> +    public byte[] ssn() {
Thank you teacher for the suggestion. Is it an acceptable way that change the method name to show() to display the desensitized social security number?

2021-12-04 05:09 UTC, XueleiFan commented on src/main/java/co/ivi/jus/record/review/songor/SocialSecurityNumber.java
> +    public byte[] ssn() {
A new method is fine. The toString() is too common to be used in log if we cannot handle the sensitive information properly.

2021-12-04 05:14 UTC, XueleiFan approved these changes
Looks  good to me, except a minor coding style comment.  Anyway, please feel free to make an update if you want to accept it.  I would like to merge your PR now.

2021-12-04 05:14 UTC, XueleiFan commented on src/main/java/co/ivi/jus/sealed/review/songor/Shape.java
> +        return shape instanceof Square || shape instanceof Rectangle rectangle && rectangle.length == rectangle.width;
Normally, we should keep each line less than or equal to 80 or 120 characters.  Otherwise, it may be not easy for some code readers.

2021-12-04 05:18 UTC, merged