add string-literal.jsh
XueleiFan/java-up pull request #5
Opened 2021-11-19 02:52 UTC by wangkang09

https://github.com/wangkang09/java-up

2021-11-19 05:29 UTC, XueleiFan requested changes
Looks good to me, except the update in .gitignore.

2021-11-19 05:29 UTC, XueleiFan commented on .gitignore
> +.idea
Please don't ignore the .idea directory, which could be useful for other users.   I would suggest removing this update from the pull request.

2021-11-19 05:29 UTC, XueleiFan commented on src/main/java/co/ivi/jus/jshell/review/wangkang/string-literal.jsh
> +"hello1" == "hello" + new String("1");//false，地址不一样
Hm, a nice test!

2021-11-19 05:48 UTC, wangkang09 commented on .gitignore
> +.idea
ok, causeof some changes happend in .idea directory when i run the project..

2021-11-19 05:51 UTC, wangkang09 commented on src/main/java/co/ivi/jus/jshell/review/wangkang/string-literal.jsh
> +"hello1" == "hello" + new String("1");//false，地址不一样
jshell is realy a nice tool to do some small test!

2021-11-21 05:17 UTC, XueleiFan approved these changes
Looks good to me.  Thanks!

2021-11-21 05:17 UTC, merged