Sealed Demo.
XueleiFan/java-up pull request #8
Opened 2021-11-22 13:50 UTC by pruidong

Use instance pattern matching (preview), this feature comes from JDK17. Please enable JDK17 preview.

2021-11-22 13:51 UTC, pruidong commented
Instance pattern matching (preview): https://openjdk.java.net/jeps/406

2021-11-23 15:48 UTC, XueleiFan requested changes

2021-11-23 15:48 UTC, XueleiFan commented on src/main/java/co/ivi/jus/sealed/review/puruidong/Shape.java
> +        System.out.println(getInstanceName(circle));
相同的类，不同的对象，会对输出结果有影响吗？这样的输出结果，你想验证什么呢？

2021-11-23 16:05 UTC, pruidong commented on src/main/java/co/ivi/jus/sealed/review/puruidong/Shape.java
> +        System.out.println(getInstanceName(circle));
把几个判断实例的方法整合到一起之后,我暂时没想到比较好的办法来确定实例来自某个类,在本地测试过不同对象输出结果一致.

2021-11-24 03:26 UTC, XueleiFan commented on src/main/java/co/ivi/jus/sealed/review/puruidong/Shape.java
> +        System.out.println(getInstanceName(circle));
好的，如果你想好了，可以回头再来改动。

2021-11-24 03:26 UTC, XueleiFan approved these changes
Looks good.  Thanks!

2021-11-24 03:27 UTC, merged